# Generated by Django 4.1 on 2022-09-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TPangkat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_pertek', models.CharField(max_length=50)),
                ('tgl_pertek', models.DateField()),
                ('nomor_sk', models.CharField(max_length=50)),
                ('tgl_sk', models.DateField()),
                ('mk_bulan', models.IntegerField(null=True)),
                ('mk_tahun', models.IntegerField(null=True)),
                ('tmt_pangkat', models.DateField()),
                ('dokument', models.FileField(upload_to='dokumen/upload/pangkat')),
            ],
            options={
                'db_table': 'TPangkat',
                'managed': False,
            },
        ),
    ]
