# Generated by Django 4.1 on 2022-09-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arsip', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tpangkat',
            table='T_Pangkat',
        ),
    ]
